@startuml BulletinsUseCaseDiagram
left to right direction 
actor "Veřejnost" as V
 
package Aplikace-Úřední_desky { 
  usecase "Přehled poskytování dat právními formami" as prehled
  usecase "Zobrazení aktuálních informací určité tématiky z konkrétní úřední desky" as zobrazeni
  usecase "Vyhledání úřední desky ze znalosti geografické polohy poskytovatele." as vyhledani

}


V --> prehled

V --> zobrazeni

V --> vyhledani


@enduml
