@startuml BulletinsUseCaseDiagram
left to right direction 
actor "Veřejnost" as V
actor "Poskytovatel dat" as P
actor "Novinář" as N
 
package Aplikace-Úřední_desky { 
  usecase "UC1: Přehled poskytování dat právními formami" as prehled
  usecase "UC2: Zobrazení aktuálních informací určité tématiky z konkrétní úřední desky" as zobrazeni
  usecase "UC3: Vyhledání úřední desky ze znalosti geografické polohy poskytovatele." as vyhledani
  usecase "UC4: Ověření korektního poskytování dat " as overeni
  usecase "UC5: Zjištění stavu poskytovaných dat v rámci právní formy." as zjisteniStavu
  usecase "UC6: Zjištění celkové kvality poskytovaných dat" as zjisteniKvality
  
}

V --> prehled
P --> prehled
prehled <-- N

V --> zobrazeni

V --> vyhledani
P --> vyhledani
vyhledani <-- N

P --> overeni

P --> zjisteniStavu
zjisteniStavu <-- N

zjisteniKvality <-- N

@enduml
